/** Resolve the fixed DOM nodes used to assemble the application controls. */
export function readShellElements(document = globalThis.document) {
  return {
    _rightPanelStack: document.getElementById('right-context-rail'),
    _styleIndicator: document.getElementById('active-style-name'),
    _sliderPanel: document.getElementById('param-slider-panel'),
    _sliderContainer: document.getElementById('param-sliders'),
    _ppToggles: document.getElementById('pp-toggles'),
    _bloomBtn: document.getElementById('bloom-toggle'),
    _bloomSliderRow: document.getElementById('bloom-slider-row'),
    _bloomSlider: document.getElementById('bloom-intensity-slider'),
    _bloomSliderValue: document.getElementById('bloom-intensity-value'),
    _sharpenBtn: document.getElementById('sharpen-toggle'),
    _sharpenSliderRow: document.getElementById('sharpen-slider-row'),
    _sharpenSlider: document.getElementById('sharpen-intensity-slider'),
    _sharpenSliderValue: document.getElementById('sharpen-intensity-value'),
    _hudBtn: document.getElementById('hud-toggle'),
    _hudLayoutRow: document.getElementById('hud-layout-row'),
    _hudLayoutSelect: document.getElementById('hud-layout-select'),
    _detectionSliderRow: document.getElementById('detection-slider-row'),
    _detectionDensitySlider: document.getElementById(
      'detection-density-slider',
    ),
    _detectionDensityValue: document.getElementById('detection-density-value'),
    _detectionAllocationRow: document.getElementById(
      'detection-allocation-row',
    ),
    _detectionFadeRow: document.getElementById('detection-fade-row'),
    _detectionFadeSlider: document.getElementById('detection-fade-slider'),
    _detectionFadeValue: document.getElementById('detection-fade-value'),
    _detectionOpacityRow: document.getElementById('detection-opacity-row'),
    _detectionOpacitySlider: document.getElementById(
      'detection-opacity-slider',
    ),
    _detectionOpacityValue: document.getElementById('detection-opacity-value'),
    _celestialBtn: document.getElementById('celestial-toggle'),
    _scopeBtn: document.getElementById('scope-toggle'),
    _scopeFeatherSlider: document.getElementById('scope-feather-slider'),
    _scopeFeatherValue: document.getElementById('scope-feather-value'),
    _mapStackChips: document.getElementById('map-stack-chips'),
    _mapStackStatus: document.getElementById('map-stack-status'),
    _cleanViewBtn: document.getElementById('clean-view-toggle'),
    _cleanViewExitBtn: document.getElementById('clean-view-exit'),
    _dataPanel: document.getElementById('data-panel'),
    _scenePanel: document.getElementById('scene-panel'),
    _cockpitUtilityControls: document.getElementById(
      'cockpit-utility-controls',
    ),
    _cockpitDisplayToggleBtn: document.getElementById(
      'cockpit-display-toggle-btn',
    ),
    _cockpitDisplayPanel: document.getElementById('cockpit-display-panel'),
    _globalContextFlightsBtn: document.getElementById(
      'global-context-flights-btn',
    ),
    _globalContextMissionsBtn: document.getElementById(
      'global-context-missions-btn',
    ),
    _contextModeStandby: document.getElementById('context-mode-standby'),
    _contextFlightsView: document.getElementById('context-flights-view'),
    _contextMissionsView: document.getElementById('context-missions-view'),
    _installationsSearchBtn: document.getElementById(
      'installations-search-btn',
    ),
    _leftPanelStack: document.getElementById('left-panel-stack'),
    _shareBtn: document.getElementById('share-btn'),
    _tiltMapBtn: document.getElementById('tilt-map-view'),
    _northUpBtn: document.getElementById('north-up-view'),
    _clearSelectedLayersBtn: document.getElementById('clear-selected-layers'),
    _globalLoadingStatus: document.getElementById('global-loading-status'),
    _globalLoadingLabel: document.getElementById('global-loading-label'),
    _globalLoadingDetail: document.getElementById('global-loading-detail'),
    _resetGlobeBtn: document.getElementById('reset-globe-view'),
    _cockpitResetGlobeBtn: document.getElementById('cockpit-reset-globe'),
    _styleButtons: document.getElementById('style-buttons'),
    _toast: document.getElementById('toast'),
    _locationSearch: document.getElementById('location-search'),
    _searchToggle: document.getElementById('search-toggle'),
    _locationPills: document.getElementById('location-pills'),
    _poiRow: document.getElementById('poi-row'),
    _locationBarDivider: document.getElementById('location-bar-divider'),
    _styleMiniValue: document.getElementById('style-mini-value'),
    _locationMiniCity: document.getElementById('location-mini-city'),
    _locationMiniPoi: document.getElementById('location-mini-poi'),
    _safeFrameOverlay: document.getElementById('safe-frame-overlay'),
    _safeFrameBox: document.getElementById('safe-frame-box'),
    _detectionBtn: document.getElementById('detection-toggle'),
    _models3dBtn: document.getElementById('models3d-toggle'),
    _models3dModeRow: document.getElementById('models3d-mode-row'),
  };
}
