// Generated by scripts/generate-oil-stops.mjs from investigations/02-oil-system/geography.json.
// Do not edit by hand: change the source and regenerate. `npm run check:generated` fails on drift.

/** A sourced label anchor for guided reading. Never a boundary, route or vessel position. */
export interface OilStop {
  readonly id: string;
  readonly entityId: string;
  readonly label: string;
  readonly latitude: number;
  readonly longitude: number;
  readonly precision: string;
  readonly role: string;
  readonly whyItMatters: string;
  readonly caveat: string;
  readonly sourceTitle: string;
  readonly sourceUrl: string;
  readonly checkedOn: string;
}

/** A sourced illustrative line built from anchor-point coordinates. */
export interface OilRoute {
  readonly id: string;
  readonly entityId: string;
  readonly label: string;
  readonly points: readonly {
    readonly latitude: number;
    readonly longitude: number;
  }[];
  readonly precision: string;
  readonly role: string;
  readonly whyItMatters: string;
  readonly caveat: string;
  readonly sourceTitle: string;
  readonly sourceUrl: string;
  readonly checkedOn: string;
}

export interface OilGeography {
  readonly title: string;
  readonly framing: string;
  readonly stops: readonly OilStop[];
  readonly routes: readonly OilRoute[];
}

export const OIL_GEOGRAPHY: OilGeography = {
  title: 'Places and corridors that organize the current oil brief',
  framing:
    "Stops are sourced label anchors for guided reading, not boundaries, pipeline routes, shipping tracks or cargo locations. Routes are sourced illustrative lines built from anchor-point coordinates, not vessel tracks, pipeline as-built paths, precise canal centerlines or capacity/flow claims; each route's caveat says exactly what it approximates.",
  stops: [
    {
      id: 'O-G01',
      entityId: 'oil-hormuz',
      label: 'Strait of Hormuz',
      latitude: 26.6,
      longitude: 56.5,
      precision: 'representative_label_point',
      role: 'Persian Gulf exit',
      whyItMatters:
        "The brief's central disruption measure is the estimated change in oil flow through Hormuz.",
      caveat:
        'A strait is an area, not a point. This anchor must not be read as a route or vessel position.',
      sourceTitle:
        'Wikidata Q79883 — coordinate location; EIA Figure 4 supplies geographic context',
      sourceUrl: 'https://www.wikidata.org/wiki/Q79883',
      checkedOn: '2026-09-22',
    },
    {
      id: 'O-G02',
      entityId: 'oil-bab',
      label: 'Bab el-Mandeb',
      latitude: 12.583333,
      longitude: 43.333333,
      precision: 'representative_label_point',
      role: 'Red Sea southern entrance',
      whyItMatters:
        'Its aggregate flow rose in the brief window, providing evidence of changed route use without proving one-for-one rerouting.',
      caveat:
        'A strait is an area, not a point. Aggregate movement cannot identify displaced Hormuz cargoes.',
      sourceTitle:
        'Wikidata Q83318 — coordinate location; EIA Figure 6 supplies geographic context',
      sourceUrl: 'https://www.wikidata.org/wiki/Q83318',
      checkedOn: '2026-09-22',
    },
    {
      id: 'O-G03',
      entityId: 'oil-malacca',
      label: 'Strait of Malacca',
      latitude: 2.833056,
      longitude: 101.036944,
      precision: 'representative_label_point',
      role: 'Indian–Pacific connection',
      whyItMatters:
        'It connects the global chokepoint view to East Asian import demand and the China evidence in this brief.',
      caveat:
        'A single label point cannot represent the roughly 930-kilometre strait or any individual voyage.',
      sourceTitle:
        'Wikidata Q48359 — coordinate location; EIA Figure 2 supplies geographic context',
      sourceUrl: 'https://www.wikidata.org/wiki/Q48359',
      checkedOn: '2026-09-22',
    },
    {
      id: 'O-G04',
      entityId: 'oil-yanbu',
      label: 'King Fahd Industrial Port, Yanbu',
      latitude: 23.950833,
      longitude: 38.2225,
      precision: 'facility_point',
      role: 'Red Sea export outlet',
      whyItMatters:
        "Yanbu is the export-side destination of Saudi Arabia's East-West crude pipeline in the current graph.",
      caveat:
        "The fixture's broader Yanbu terminal entity is anchored to the named industrial port; pipeline route geometry is still absent.",
      sourceTitle: 'Wikidata Q12246916 — GNS-referenced coordinate location',
      sourceUrl: 'https://www.wikidata.org/wiki/Q12246916',
      checkedOn: '2026-09-22',
    },
    {
      id: 'O-G05',
      entityId: 'oil-sunda',
      label: 'Sunda Strait',
      latitude: -5.970278,
      longitude: 105.769722,
      precision: 'representative_label_point',
      role: 'Smaller Pacific-side alternative to Malacca',
      whyItMatters:
        'The brief records Sunda as a smaller alternative route around the Strait of Malacca, without established capacity or use in the observation window.',
      caveat:
        'A strait is an area, not a point. This anchor must not be read as a route, a capacity claim or evidence that any cargo actually used Sunda instead of Malacca.',
      sourceTitle:
        'Wikidata Q192790 — coordinate location (Geographic Names Server); EIA Figure 2 supplies alternative-route context',
      sourceUrl: 'https://www.wikidata.org/wiki/Q192790',
      checkedOn: '2026-09-22',
    },
    {
      id: 'O-G06',
      entityId: 'oil-lombok',
      label: 'Lombok Strait',
      latitude: -8.5,
      longitude: 115.833333,
      precision: 'representative_label_point',
      role: 'Smaller Pacific-side alternative to Malacca',
      whyItMatters:
        'The brief records Lombok as a second smaller alternative route around the Strait of Malacca, without established capacity or use in the observation window.',
      caveat:
        'A strait is an area, not a point. This anchor must not be read as a route, a capacity claim or evidence that any cargo actually used Lombok instead of Malacca.',
      sourceTitle:
        'Wikidata Q745025 — coordinate location (Geographic Names Server); EIA Figure 2 supplies alternative-route context',
      sourceUrl: 'https://www.wikidata.org/wiki/Q745025',
      checkedOn: '2026-09-22',
    },
  ],
  routes: [
    {
      id: 'O-R01',
      entityId: 'oil-suez-sumed',
      label: 'Suez Canal / SUMED corridor',
      points: [
        {
          latitude: 29.92,
          longitude: 32.55,
        },
        {
          latitude: 31.26,
          longitude: 32.35,
        },
      ],
      precision: 'canal_terminus_line',
      role: 'Red Sea to Mediterranean corridor',
      whyItMatters:
        "The brief describes this combined canal-and-pipeline corridor as the Red Sea's connection to the Mediterranean, an alternative to routing around the Cape of Good Hope.",
      caveat:
        "This line joins the Suez Canal's sourced southern (Red Sea) and northern (Mediterranean) terminus coordinates in a straight segment; the canal itself curves through the Bitter Lakes and does not run straight. The SUMED pipeline (Ain Sokhna, Wikidata Q405881, to Sidi Kerir, Wikidata Q16121570) runs a separate, roughly parallel corridor that is not drawn here. Neither line is a vessel track, a pipeline as-built route or a flow/capacity claim.",
      sourceTitle:
        'Wikidata Q899 — Suez Canal coordinate location (southern/northern terminus); EIA Suez, SUMED, Bab el-Mandeb and Cape routing note supplies the corridor context',
      sourceUrl: 'https://www.wikidata.org/wiki/Q899',
      checkedOn: '2026-09-22',
    },
    {
      id: 'O-R03',
      entityId: 'oil-myanmar-china-pipeline',
      label: 'Myanmar–China crude oil pipeline',
      points: [
        {
          latitude: 19.359,
          longitude: 93.6552,
        },
        {
          latitude: 25.043333,
          longitude: 102.706111,
        },
      ],
      precision: 'illustrative_corridor_endpoints',
      role: 'Overland alternative to the Malacca sea route',
      whyItMatters:
        'The brief records this pipeline as an alternative that moves Middle Eastern crude to southwest China without transiting Malacca, without establishing its operating throughput or spare capacity.',
      caveat:
        "This line joins the sourced Kyaukphyu-area terminal point (Maday Island) with the sourced Kunming endpoint in a straight segment. The pipeline's actual path runs overland through Mandalay and the Ruili border crossing, not a straight line, and this geometry makes no throughput or capacity claim.",
      sourceTitle:
        'Wikidata Q117253729 — Maday Island/Kyaukphyu terminal coordinate location; Wikidata Q182852 — Kunming coordinate location; EIA alternatives-to-Malacca note supplies the corridor context',
      sourceUrl: 'https://www.wikidata.org/wiki/Q117253729',
      checkedOn: '2026-09-22',
    },
  ],
};
