"""Generate an explicit SQL migration for additions to an imported investigation.

The generator reads the retained local seed, rejects changed or removed existing
records, and emits inserts for new sources/claims plus a new seed snapshot. It is
a development tool; the generated SQL remains the reviewed migration artifact.
"""

import argparse
import json
from pathlib import Path
from uuid import NAMESPACE_URL, uuid5

from app.investigation import load_investigations
from app.main import INVESTIGATIONS
from app.storage.database import Database, configured_url
from app.storage.reviews import fingerprint, seed_payload


def quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def compact(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def records_by_id(records: list[dict]) -> dict[str, dict]:
    return {record["id"]: record for record in records}


def additions(previous: list[dict], current: list[dict], label: str) -> list[dict]:
    old = records_by_id(previous)
    new = records_by_id(current)
    removed = old.keys() - new.keys()
    changed = {
        record_id
        for record_id in old.keys() & new.keys()
        if old[record_id] != new[record_id]
    }
    if removed or changed:
        raise ValueError(
            f"{label} is not additive; removed={sorted(removed)}, changed={sorted(changed)}"
        )
    return [record for record in current if record["id"] not in old]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("case_id")
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    url = configured_url()
    if not url:
        raise RuntimeError(
            "A local Nexus database is required to compare the retained seed"
        )
    investigation = next(
        item
        for item in load_investigations(INVESTIGATIONS)
        if item.pack.case_id == args.case_id
    )
    target = seed_payload(investigation)
    with Database(url).connect() as connection:
        row = connection.execute(
            "SELECT payload FROM investigation_seed WHERE case_id = %s", (args.case_id,)
        ).fetchone()
    if not row:
        raise RuntimeError(f"No retained seed for {args.case_id}")
    previous = row["payload"]

    for key in ("schema_version", "case_id", "checked_on", "scope", "verdict"):
        if previous["pack"][key] != target["pack"][key]:
            raise ValueError(
                f"Pack field changed and requires a custom migration: {key}"
            )
    new_sources = additions(
        previous["pack"]["sources"], target["pack"]["sources"], "sources"
    )
    additions(previous["pack"]["entities"], target["pack"]["entities"], "entities")
    new_claims = additions(
        previous["pack"]["claims"], target["pack"]["claims"], "claims"
    )
    additions(previous["pack"]["events"], target["pack"]["events"], "events")
    additions(previous["questions"], target["questions"], "questions")
    additions(
        previous["pack"]["briefing"]["metrics"],
        target["pack"]["briefing"]["metrics"],
        "metrics",
    )
    if not new_sources and not new_claims:
        raise ValueError("No new persisted source or claim records")

    digest = fingerprint(target)
    lines = [
        "-- Generated by scripts/generate-additive-migration.py; review before applying.",
        "-- A fresh database has no retained seed yet, so every addition is skipped;",
        "-- normal fixture initialization imports the complete current pack afterward.",
        "ALTER TABLE investigation_seed DISABLE TRIGGER seed_immutable;",
        f"UPDATE investigation_seed SET payload = {quote(compact(target))}::jsonb,",
        f"    fingerprint = {quote(digest)} WHERE case_id = {quote(args.case_id)};",
        "ALTER TABLE investigation_seed ENABLE TRIGGER seed_immutable;",
        "",
    ]
    for source in new_sources:
        lines.extend(
            [
                "INSERT INTO evidence_sources(id, payload, content_hash)",
                f"SELECT {quote(source['id'])}, {quote(compact(source))}::jsonb, {quote(fingerprint(source))}",
                "WHERE EXISTS (",
                "    SELECT 1 FROM investigation_seed",
                f"    WHERE case_id = {quote(args.case_id)}",
                ")",
                "ON CONFLICT (id) DO NOTHING;",
                "",
            ]
        )
    for claim in new_claims:
        proposal_id = uuid5(NAMESPACE_URL, f"nexus:{args.case_id}:{claim['id']}")
        lines.extend(
            [
                "INSERT INTO knowledge_assertions(id, case_id)",
                f"SELECT {quote(claim['id'])}, {quote(args.case_id)}",
                "WHERE EXISTS (",
                "    SELECT 1 FROM investigation_seed",
                f"    WHERE case_id = {quote(args.case_id)}",
                ")",
                "ON CONFLICT (id) DO NOTHING;",
                "INSERT INTO knowledge_proposals",
                "    (id, claim_id, base_revision, payload, author, reason, request_hash)",
                "SELECT * FROM (VALUES (",
                f"    {quote(str(proposal_id))}::uuid, {quote(claim['id'])}, 0, {quote(compact(claim))}::jsonb,",
                "    'Research fixture import',",
                "    'Imported as a candidate; application review has not occurred.',",
                f"    {quote(digest)}",
                ")) AS addition(id, claim_id, base_revision, payload, author, reason, request_hash)",
                "WHERE EXISTS (",
                "    SELECT 1 FROM investigation_seed",
                f"    WHERE case_id = {quote(args.case_id)}",
                ")",
                "ON CONFLICT (id) DO NOTHING;",
            ]
        )
        for source_id in claim["evidence_ids"]:
            lines.extend(
                [
                    "INSERT INTO knowledge_proposal_evidence(proposal_id, source_id)",
                    f"SELECT {quote(str(proposal_id))}::uuid, {quote(source_id)}",
                    "WHERE EXISTS (",
                    "    SELECT 1 FROM investigation_seed",
                    f"    WHERE case_id = {quote(args.case_id)}",
                    ")",
                    "ON CONFLICT (proposal_id, source_id) DO NOTHING;",
                ]
            )
        lines.append("")
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {args.output}: {len(new_sources)} sources, {len(new_claims)} claims")


if __name__ == "__main__":
    main()
