"""Render a normalisation release as a human review sheet (docs/normalisation-review.md).

The generated part sits above the marker line; anything below it is hand-written analysis and is
preserved when the sheet is regenerated.

    python scripts/render_normalisation_review.py            # rewrites docs/normalisation-review.md
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RELEASES = ROOT / "normalisation" / "releases"


def _latest() -> Path:
    def order(path: Path):
        match = re.match(r"(\d{4}-\d{2}-\d{2})(?:-r(\d+))?$", path.stem)
        return (match.group(1), int(match.group(2) or 1)) if match else ("", 0)

    return max(RELEASES.glob("*.json"), key=order)


DEFAULT_RELEASE = _latest()
SHEET = ROOT / "docs" / "normalisation-review.md"
MARKER = (
    "<!-- assistant analysis: hand-written below this line; kept on regeneration -->"
)

DECISIONS = """\
## Decisions for you

This sheet is a proposal, prepared by the assistant. Nothing here is accepted until you say so.

1. **Vocabulary lists** (approved 2026-09-24) in `normalisation/vocabulary-v1.json` (predicates, statuses, classes, measures, units, entity categories). `observed` is defined but assigned to nothing.
2. **The 44-claim table below** (reviewed 2026-09-24).
3. **Canonical names** (settled 2026-09-24): the shorthand form of each country name, for example "China", "United States", "United Arab Emirates".
4. **Russia and Iran** (settled 2026-09-24): added to the registry as `place/russia` and `place/iran`, so their O-M11 measurements link to them. They have no legacy alias.
5. **The two date reinterpretations** (settled 2026-09-24): O-C23 (stock snapshot as an instant, 2026-09-11) and O-C24 (capacity snapshot as an instant, 2026-01-01).
6. **O-C07's epistemic label** (`estimated`) and O-M10's third point (`reported` and provisional), settled 2026-09-24.
7. **The `observed` rule** (settled 2026-09-24): nothing is `observed`, because every claim rests on a publisher's report or estimate, not on a direct measurement by Nexus.
"""


def _cell(text: object) -> str:
    return (
        str(text if text not in (None, "") else "-")
        .replace("|", "\\|")
        .replace("\n", " ")
    )


def _time(t: dict) -> str:
    if t["valid_kind"] == "interval":
        return f"{t['valid_start']} to <{t['valid_end_exclusive']} ({t['precision']})"
    if t["valid_kind"] == "instant":
        return f"at {t['valid_at']} ({t['precision']})"
    return "unknown"


def _table(header: list[str], rows: list[list[object]]) -> list[str]:
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines += ["| " + " | ".join(_cell(c) for c in row) + " |" for row in rows]
    return lines


def _legacy() -> dict[tuple[str, str], dict]:
    legacy = {}
    for directory in sorted((ROOT / "investigations").iterdir()):
        pack = directory / "evidence-pack.json"
        if pack.is_file():
            data = json.loads(pack.read_text("utf-8"))
            for claim in data["claims"]:
                legacy[(data["case_id"], claim["id"])] = claim
    return legacy


def render(release_path: Path) -> str:
    release = json.loads(release_path.read_text("utf-8"))
    legacy = _legacy()
    out = [
        "# Normalisation review sheet",
        "",
        (
            f"Release `{release['release_id']}`, vocabulary {release['vocabulary_version']}. "
            "Generated by `scripts/render_normalisation_review.py`; do not edit above the marker."
        ),
        "",
        DECISIONS,
        "## Claims",
        "",
        (
            "Old labels are shown so you can see what changed. `REVIEW` marks a claim whose "
            "meaning needs your judgement; the reason is in its note. Qualifiers hold detail "
            "that no predicate should carry (material, scope, attribution)."
        ),
        "",
    ]
    rows = []
    for c in release["claims"]:
        old = legacy[(c["case_id"], c["claim_id"])]
        rows.append(
            [
                c["claim_id"],
                f"{old['predicate']} / {old['kind']}",
                c["predicate"],
                c["epistemic_status"],
                c["content_type"],
                c["modality"]
                + (
                    ""
                    if c["release_status"] == "unspecified"
                    else f", {c['release_status']}"
                ),
                "; ".join(f"{k}={v}" for k, v in c["qualifiers"].items()),
                _time(c["temporal"])
                + (
                    " (reinterpreted)"
                    if c["temporal"]["state"] == "proposed_reinterpretation"
                    else ""
                ),
                ("REVIEW: " if c["needs_semantic_review"] else "") + (c["note"] or ""),
            ]
        )
    out += _table(
        [
            "Claim",
            "Old predicate / kind",
            "Predicate",
            "Status",
            "Content",
            "Modality",
            "Qualifiers",
            "Period",
            "Flag and note",
        ],
        rows,
    )
    out += [
        "",
        "## Entities",
        "",
        "Legacy IDs keep resolving through aliases; no historical endpoint changes.",
        "",
    ]
    out += _table(
        ["Canonical ID", "Name", "Category / subtype", "Legacy alias (case: id)"],
        [
            [
                f"`{e['canonical_id']}`",
                e["name"],
                f"{e['category']} / {e['subtype']}",
                ", ".join(f"{a['case_id']}: {a['legacy_id']}" for a in e["aliases"]),
            ]
            for e in release["entities"]
        ],
    )
    out += ["", "## Sources", ""]
    out += _table(
        [
            "Source",
            "Case",
            "Publisher class",
            "Document class",
            "Legacy retrieval label",
        ],
        [
            [
                s["source_id"],
                s["case_id"],
                s["publisher_class"],
                s["document_class"],
                s["legacy_reported_method"],
            ]
            for s in release["sources"]
        ],
    )
    out += [
        "",
        "## Measurements",
        "",
        "Values keep their original decimal text. Claim links appear only where the recommendation supports them.",
        "",
    ]
    out += _table(
        [
            "ID",
            "Pack label",
            "Value",
            "Measure",
            "Entity",
            "Period",
            "Status",
            "Claims",
            "Note",
        ],
        [
            [
                m["id"].split(":", 1)[1],
                m["original_label"],
                m["value_text"],
                m["measure"],
                m["entity"],
                _time(m["temporal"]),
                m["epistemic_status"]
                + (
                    ""
                    if m["release_status"] == "unspecified"
                    else f", {m['release_status']}"
                ),
                ", ".join(m["claim_ids"]),
                m["note"],
            ]
            for m in release["measurements"]
        ],
    )
    return "\n".join(out) + "\n"


def main() -> int:
    generated = render(DEFAULT_RELEASE)
    kept = ""
    if SHEET.exists() and MARKER in (existing := SHEET.read_text("utf-8")):
        kept = existing.split(MARKER, 1)[1]
    SHEET.write_text(generated + "\n" + MARKER + kept, encoding="utf-8")
    print(f"wrote {SHEET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
